Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace project.Models
{
    public class Room
    {
        [StringLength(10)]
        
        [Display(Name = "房間名稱")]
        public string RoomName { get; set; }

        [StringLength(1)]
        [Display(Name = "樓層")]
        public string Floor { get; set; }
        [Key]
        [StringLength(3)]
        [Display(Name = "房間號碼")]
        public string RoomNumber { get; set; }

        [StringLength(10)]
        [Display(Name = "房間類型")]
        public string RoomType { get; set; }
        [Display(Name = "單價")]

        public int DayPrice { get; set; }
        [Display(Name = "周末價格")]

        public int WeekendPrice { get; set; }
        [Display(Name = "折扣")]

        public decimal Discount { get; set; }
        [Display(Name = "服務費")]
        public decimal ServiceFee { get; set; }


    }
}

Controllers/RoomsController.cs
using Microsoft.AspNetCore.Mvc;
using project.Data;
using project.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;

namespace project.Controllers
{
    public class RoomsController : Controller
    {
        public IDataAccess _dataAccess;
        public RoomsController(IDataAccess dataAccess) //讓控制器可以使用 預先設計的方法
        {
            _dataAccess = dataAccess;
        }
        public IActionResult Roomselect()
        {
            return View();
        }
        public IActionResult Singleroom(int Id) //若方法內有一變數則需傳入一變數
        {
            var introductionroom = _dataAccess.roomIntroduction(Id);
            
            return View(introductionroom);
        }
        public IActionResult Roomsmasterpage()
        {
            return View();
        }

        public IActionResult Singleindex()
        {
            return View();
        }
        public IActionResult Roomselectindex()
        {
            return View();
        }
        public IActionResult Tripleindex()
        {
            return View();
        }
        public IActionResult Quadruplerindex()
        {
            return View();
        }
    }
}

Views/Rooms/Quadruplerindex.cshtml
@{
    ViewData["Title"] = "ROOMS";
}


@section css{
    <link rel="stylesheet" href="~/css/roomstyle_select.css">
}

<section id="poem">
    <div class="poemsup">
        <h1>四人套房</h1>
    </div>
    <hr class="hr01">
    <hr class="hr02">
    <div class="poemsdown">
        享受黑膠唱盤與精選唱片，<br>
        襯著光影或夜色盡興談心，<br>
        把握與家人好友出遊的幸福時光。
    </div>
</section>
<article id="allroom">
    <section id="familyroom">
        <div class="mainImg">
            <img src="~/img/Room/family_room1.jpg" alt="family_room">
        </div>
        <div class="roomContent">
            <div class="roomtxt">
                <h2>商務四人房</h2>
                專屬商務及團體設計的旅居商務四人房，寬敞空間及良好隔音設備,<br />
                即便是在鬧區，也能享有靜謐的住宿體驗。
            </div>
            <div>
                <ul class="room_icon">
                    <li>
                        <i><img src="~/img/use/bed.png" title="雙人床" alt="雙人床"></i>
                        <p>雙人床</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/tv.png" title="液晶電視" alt="液晶電視"></i>
                        <p>液晶電視</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/movie.png" title="黑膠唱盤" alt="黑膠唱盤"></i>
                        <p>黑膠唱盤</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/shower.png" title="淋浴間" alt="淋浴間"></i>
                        <p>淋浴間</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/slippers.png" title="室內皮拖鞋" alt="室內皮拖鞋"></i>
                        <p>室內皮拖鞋</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/bpa-free.png" title="迎賓氣泡水" alt="迎賓氣泡水"></i>
                        <p>迎賓氣泡水</p>
                    </li>
                </ul>
                <div class="roomView">
                    <a asp-controller="Rooms" asp-action="Singleroom"  asp-route-Id="400">VIEW MORE</a>
                </div>
            </div>
        </div>
    </section>
    <section id="familyroom2">
        <div class="mainImg">
            <img src="~/img/Room/family_room2.jpg" alt="family_room">
        </div>
        <div class="roomContent">
            <div class="roomtxt">
                <h2>標準四人房</h2>
                為家庭及團體設計的旅居親子房,<br />
                明亮採光，寬敞舒適的空間，與家人朋友度過一個美好的假期。

            </div>
            <div>
                <ul class="room_icon">
                    <li>
                        <i><img src="~/img/use/bed.png" title="加大雙人床" alt="加大雙人床"></i>
                        <p>加大雙人床</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/tv.png" title="液晶電視" alt="液晶電視"></i>
                        <p>液晶電視</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/movie.png" title="黑膠唱盤" alt="黑膠唱盤"></i>
                        <p>黑膠唱盤</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/clean.png" title="浴缸" alt="浴缸"></i>
                        <p>浴缸</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/slippers.png" title="室內皮拖鞋" alt="室內皮拖鞋"></i>
                        <p>室內皮拖鞋</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/bpa-free.png" title="迎賓氣泡水" alt="迎賓氣泡水"></i>
                        <p>迎賓氣泡水</p>
                    </li>
                </ul>
                <div class="roomView">
                    <a asp-controller="Rooms" asp-action="Singleroom"  asp-route-Id="401">VIEW MORE</a>
                </div>
            </div>
        </div>
    </section>
	<br>
    <br>
    <br>
    <div class="back">
        <a asp-controller="Rooms" asp-action="Roomsmasterpage">
            <i class="fas fa-hand-point-left"></i> Back
        </a>
    </div>
</article>

Views/Rooms/Roomselectindex.cshtml
@{
    ViewData["Title"] = "ROOMS";
}


@section css{
    <link rel="stylesheet" href="~/css/roomstyle_select.css">
}

<section id="poem">
    <div class="poemsup">
        <h1>雙人套房</h1>
    </div>
    <hr class="hr01">
    <hr class="hr02">
    <div class="poemsdown">
        輕鬆入住應有盡有的精緻房型，<br>
        提供一大床與雙單床兩種選擇，<br>
        無論雙人出遊、商務之旅，都能愜意成行！<br>
    </div>
</section>
<article id="allroom">
    <section id="doubleroom">
        <div class="mainImg">
            <img src="~/img/Room/double_room1.jpg" alt="double_room">
        </div>
        <div class="roomContent">
            <div class="roomtxt">
                <h2>雅緻雙人房</h2>
                中型雙床房，適合老友結伴的旅行，<br />
                獨立浴室與書桌也成為絕對的必要貼心。
            </div>
            <div>
                <ul class="room_icon">
                    <li>
                        <i><img src="~/img/use/safe.png" title="保險箱" alt="保險箱"></i>
                        <p>保險箱</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/tv.png" title="液晶電視" alt="液晶電視"></i>
                        <p>液晶電視</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/movie.png" title="黑膠唱盤" alt="黑膠唱盤"></i>
                        <p>黑膠唱盤</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/shower.png" title="淋浴間" alt="淋浴間"></i>
                        <p>淋浴間</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/slippers.png" title="室內皮拖鞋" alt="室內皮拖鞋"></i>
                        <p>室內皮拖鞋</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/bpa-free.png" title="迎賓氣泡水" alt="迎賓氣泡水"></i>
                        <p>迎賓氣泡水</p>
                    </li>
                </ul>
                <div class="roomView">
                    <a asp-controller="Rooms" asp-action="Singleroom"  asp-route-Id="200">VIEW MORE</a>
                </div>
            </div>
        </div>
    </section>
    <section id="doubleroom2">
        <div class="mainImg">
            <img src="~/img/Room/double_room2.jpg" alt="double_room">
        </div>
        <div class="roomContent">
            <div class="roomtxt">
                <h2>高級雙人房</h2>
                低調的奢華空間，滿足了旅行想享受一下的心情。<br />
                讓旅人休憩，回味旅程。
            </div>
            <div>
                <ul class="room_icon">
                    <li>
                        <i><img src="~/img/use/bed.png" title="加大雙人床" alt="加大雙人床"></i>
                        <p>加大雙人床</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/tv.png" title="液晶電視" alt="液晶電視"></i>
                        <p>液晶電視</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/movie.png" title="黑膠唱盤" alt="黑膠唱盤"></i>
                        <p>黑膠唱盤</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/clean.png" title="浴缸" alt="浴缸"></i>
                        <p>浴缸</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/slippers.png" title="室內皮拖鞋" alt="室內皮拖鞋"></i>
                        <p>室內皮拖鞋</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/bpa-free.png" title="迎賓氣泡水" alt="迎賓氣泡水"></i>
                        <p>迎賓氣泡水</p>
                    </li>
                </ul>
                <div class="roomView">
                    <a asp-controller="Rooms" asp-action="Singleroom"  asp-route-Id="201">VIEW MORE</a>
                </div>
            </div>
        </div>
    </section>
	<br>
    <br>
    <br>
    <div class="back">
        <a asp-controller="Rooms" asp-action="Roomsmasterpage">
            <i class="fas fa-hand-point-left"></i> Back
        </a>
    </div>
</article>

Views/Rooms/Roomsmasterpage.cshtml
@{
    ViewData["Title"] = "ROOMSMASTERPAGE";
}


@section css{
    <link rel="stylesheet" href="~/css/roomstyle_masterpage.css">
}
<section id="roomtype">
    <div class="jumbotron">
        <h1>ROOMS</h1>
        <h3>房型介紹</h3>
    </div>
</section>

<section id="poem">
    <div class="poemsup">
        <h1>旅館客房 HOTEL</h1>
    </div>
    <hr class="hr01">
    <hr class="hr02">
    <div class="poemsdown">
        在旅行中遇到的每一個人，每一件事與每一個美麗景色，<br>
        都有可能成為一生中難忘的風景。<br>
        <br>
        一路走來，<br>
        我們無法猜測迎接的會試什麼樣的風景，沒法預測目的地在哪，<br>
        可是前進的腳步卻始終不能停下，<br>
        因為時間不允許我們在任何地方停留，<br>
        只有在前進中不斷學會選擇，學會體會，學會欣賞。<br>

    </div>
</section>
<section id="roompagecard">
    <div class="room_card container">
        <div class="row room-cards-wrapper">
            <div class="roompicscard mb-5 col-sm-6 col-lg-6 col-12">	
                <figure class="card">
                    <img alt="單人房" src="~/img/Room/single_room2.jpg">
                    <figcaption class="card-footer">
                        <a class="stretched-link" asp-controller="Rooms" asp-action="Singleindex">單人房</a>
                    </figcaption>
                </figure>
            </div>
            <div class="roompicscard mb-5 col-sm-6 col-lg-6 col-12">	
                <figure class="card">
                    <img alt="雙人房" src="~/img/Room/double_room2.jpg">
                    <figcaption class="card-footer">
                        <a class="stretched-link" asp-controller="Rooms" asp-action="Roomselectindex">雙人房</a>
                    </figcaption>
                </figure>
            </div>
            <div class="roompicscard mb-5 col-sm-6 col-lg-6 col-12">	
                <figure class="card">
                    <img alt="三人房" src="~/img/Room/triple_room2.jpg">
                    <figcaption class="card-footer">
                        <a class="stretched-link" asp-controller="Rooms" asp-action="Tripleindex">三人房</a>
                    </figcaption>
                </figure>
            </div>
            <div class="roompicscard mb-5 col-sm-6 col-lg-6 col-12">	
                <figure class="card">
                    <img alt="四人房" src="~/img/Room/family_room2.jpg">
                    <figcaption class="card-footer">
                        <a class="stretched-link" asp-controller="Rooms" asp-action="Quadruplerindex">四人房</a>
                    </figcaption>
                </figure>
            </div>

        </div>
    </div>
</section>

Views/Rooms/Singleindex.cshtml
@{
    ViewData["Title"] = "ROOMS";
}


@section css{
    <link rel="stylesheet" href="~/css/roomstyle_select.css">
}
<section id="poem">
    <div class="poemsup">
        <h1>單人套房</h1>
    </div>
    <hr class="hr01">
    <hr class="hr02">
    <div class="poemsdown">
        獨享黑膠唱盤與精選唱片，<br>
        讓音樂流淌在舒適寬敞的空間，<br>
        讓一日的疲累在浴池中散去，享受低調奢華的慢旅行。
    </div>
</section>
<article id="allroom">
    <section id="singleroom">

        <div class="mainImg">
            <img src="~/img/Room/single_room1.jpg" alt="single_room">
        </div>

        <div class="roomContent">
            <h2>溫馨單人房</h2>
            倚在窗邊，欣賞著台灣味的巷弄街景。<br />
            特別適合想要個人空間與私密性的單人旅行。
            <div>
                <ul class="room_icon ">
                    <li>
                        <i><img src="~/img/use/safe.png" title="保險箱" alt="保險箱"></i>
                        <p>保險箱</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/tv.png" title="液晶電視" alt="液晶電視"></i>
                        <p>液晶電視</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/movie.png" title="黑膠唱盤" alt="黑膠唱盤"></i>
                        <p>黑膠唱盤</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/shower.png" title="淋浴間" alt="淋浴間"></i>
                        <p>淋浴間</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/slippers.png" title="室內皮拖鞋" alt="室內皮拖鞋"></i>
                        <p>室內皮拖鞋</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/freezer.png" title="迎賓氣泡水" alt="迎賓氣泡水"></i>
                        <p>迎賓氣泡水</p>
                    </li>
                </ul>
                <div class="roomView">
                    <a asp-controller="Rooms" asp-action="Singleroom"  asp-route-Id="100">VIEW MORE</a> <!--asp-route-Type  Type為控制器裡的的名稱後面為要帶入的數值-->
                </div>
            </div>
        </div>
    </section>
    <section id="singleroom2">

        <div class="mainImg">
            <img src="~/img/Room/single_room2.jpg" alt="single_room">
        </div>

        <div class="roomContent">
            <h2>高級單人房</h2>
            近乎奢侈的空間與小沙發區，是您最佳住宿選擇，<br />
            喜歡大空間的您，千萬別錯過了。
            <div>
                <ul class="room_icon ">
                    <li>
                        <i><img src="~/img/use/safe.png" title="保險箱" alt="保險箱"></i>
                        <p>保險箱</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/tv.png" title="液晶電視" alt="液晶電視"></i>
                        <p>液晶電視</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/movie.png" title="黑膠唱盤" alt="黑膠唱盤"></i>
                        <p>黑膠唱盤</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/clean.png" title="浴缸" alt="浴缸"></i>
                        <p>浴缸</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/slippers.png" title="室內皮拖鞋" alt="室內皮拖鞋"></i>
                        <p>室內皮拖鞋</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/freezer.png" title="迎賓氣泡水" alt="迎賓氣泡水"></i>
                        <p>迎賓氣泡水</p>
                    </li>
                </ul>
                <div class="roomView">
                    <a asp-controller="Rooms" asp-action="Singleroom" asp-route-Id="101">VIEW MORE</a>
                </div>
            </div>
        </div>
    </section>
	<br>
    <br>
    <br>
    <div class="back">
        <a asp-controller="Rooms" asp-action="Roomsmasterpage">
            <i class="fas fa-hand-point-left"></i> Back
        </a>
    </div>
</article>

Views/Rooms/Singleroom.cshtml
@model project.Models.RoomIntroduction

@{
    ViewData["Title"] = "Singleroom";
    var imagepath = Model.Photo; <!--讀取資料庫中的照片路徑-->
    var imagepath1 = Model.Photo1;
    var imagepath2 = Model.Photo2;

}

@section css
    {
    <link rel="stylesheet" href="~/css/roomtype.css">
}

<div class="container">
    <section id="roomtype">
        <div class="room_name">
            <h1>@Model.Description</h1>
        </div>
        <hr class="hr01">
        <hr class="hr02">
        <div class="roomtxt">
           @Html.Raw(Model.RoomTxt.Replace("\n", "<br>")) <!--raw將字串內容包起來 會轉換成html格式   replace取代 \n(換行符號)取代成<br> -->
        </div>
    </section>
    <section id="room_img">
        <div id="myCarousel" class="carousel slide" data-ride="carousel data-interval=" false"">
            <!-- 連結導引項目 -->
            <ul class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ul>
            <!--圖片顯示區, 幻燈片圖片 -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="@Url.Content(imagepath)" alt="single_room" class="img-fluid"> <!--Url.Content相對路徑轉絕對路徑  -->
                </div>
                <div class="carousel-item">
                    <img src="@Url.Content(imagepath1)" alt="bathroom" class="img-fluid">
                </div>
                <div class="carousel-item">
                    <img src="@Url.Content(imagepath2)" alt="shampoo" class="img-fluid">
                </div>
            </div>
            <!-- 前後切換連結-->
            <a class="carousel-control-prev" href="#myCarousel"
               data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#myCarousel"
               data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </section>

    <section class="roomDetails">
        <div class="rdtitle">
            <b>ROOM DETAILS</b>
            <div class="RDtitle">| 房型資訊 |</div>
        </div>
        <!--房型資訊-->

        <ul>
            @if (Model.Singlebed.Equals("有"))
            {
                <li><i class="fas fa-bed"></i> 單人床</li>
            }
            @if (Model.Doublebed.Equals("有"))
            {
                <li><i class="fas fa-bed"></i> 雙人床</li>
            }
            @if (Model.Tellphone.Equals("有"))
            {
                <li><i class="fas fa-phone-square"></i> 電話</li>            
            }
            @if (Model.TV.Equals("有"))
            {
                <li><i class="fas fa-tv"></i> 電視</li>
            }
            @if (Model.Airconditioning.Equals("有"))
            {
                <li><i class="far fa-snowflake"></i> 空調</li>
            }
            @if (Model.ShowerRoom.Equals("有"))
            {
                <li><i class="fas fa-shower"></i>  淋浴間</li>
            }
            @if (Model.Bathtub.Equals("有"))
            {
                <li><i class="fas fa-bath"></i> 浴缸</li>
            }
            @if (Model.Refrigerator.Equals("有"))
            {
        <li><i class="fas fa-compact-disc"></i> 黑膠唱片</li>
            }
        </ul>
        <div class="textbox">
            <p>每晚房價$@Model.DayPrice+10%</p>

            <p>入住時間: 15:00</p>

            <p>退房時間: 11:00</p>
            <p>入住者至少一位須年滿18歲</p>
        </div>
        <div class="order">
            <p><strong>★訂房須知★</strong></p>
            <p>旅客於辦理入住時，需提供有效信用卡授權NT$1000之保證訂金，用於支付住房費用以外之其它費用。如退房後未有其它費用產生，旅館將於退房後12小時內向銀行申請取消旅客信用卡授權。</p>
        </div>
        <form method="post" asp-controller="Reserve" asp-action="Find" asp-route-startdate="@DateTime.Now.ToString("yyyy/MM/dd")" asp-route-enddate="@DateTime.Now.AddDays(1).ToString("yyyy/MM/dd")"  asp-route-room="@Model.RoomType">
        <div class="btn">
            <input type="submit" value="立即訂房" onclick=""><!--會連到訂房頁面-->
        </div>
        </form>
    </section>


</div>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="goback">
    <a asp-controller="Rooms" asp-action="Singleindex">
        <i class="fas fa-hand-point-left"></i> Back
    </a>
</div>

Views/Rooms/Tripleindex.cshtml
@{
    ViewData["Title"] = "ROOMS";
}


@section css{
    <link rel="stylesheet" href="~/css/roomstyle_select.css">
}

<section id="poem">
    <div class="poemsup">
        <h1>三人套房</h1>
    </div>
    <hr class="hr01">
    <hr class="hr02">
    <div class="poemsdown">
        黑膠唱盤與精選唱片的享受，<br>
        音樂流淌在舒適寬敞的空間，<br>
        專屬於三人的幸福時光。
    </div>
</section>
<article id="allroom">
    <section id="tripleroom">
        <div class="mainImg">
            <img src="~/img/Room/triple_room1.jpg" alt="triple_room">
        </div>
        <div class="roomContent">
            <div class="roomtxt">
                <h2>簡約三人房</h2>
                中型三人房，巧妙運用上下舖的3張單人床方式，為旅宿帶來變化，<br />
                小沙發更提供了額外的小確幸，恰到好處的空間與合宜價格更成為高CP值的優選。
            </div>
            <div>
                <ul class="room_icon">
                    <li>
                        <i><img src="~/img/use/safe.png" title="保險箱" alt="保險箱"></i>
                        <p>保險箱</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/tv.png" title="液晶電視" alt="液晶電視"></i>
                        <p>液晶電視</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/movie.png" title="黑膠唱盤" alt="黑膠唱盤"></i>
                        <p>黑膠唱盤</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/shower.png" title="淋浴間" alt="淋浴間"></i>
                        <p>淋浴間</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/slippers.png" title="室內皮拖鞋" alt="室內皮拖鞋"></i>
                        <p>室內皮拖鞋</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/bpa-free.png" title="迎賓氣泡水" alt="迎賓氣泡水"></i>
                        <p>迎賓氣泡水</p>
                    </li>
                </ul>
                <div class="roomView">
                    <a asp-controller="Rooms" asp-action="Singleroom"  asp-route-Id="300">VIEW MORE</a>
                </div>
            </div>
        </div>
    </section>
    <section id="tripleroom2">
        <div class="mainImg">
            <img src="~/img/Room/triple_room2.jpg" alt="triple_room">
        </div>
        <div class="roomContent">
            <div class="roomtxt">
                <h2>經典三人房</h2>
                既使擺放了三張床鋪，空間依舊寬敞不顯擁擠。<br />
                適合與家人、朋友一同度過平靜的愜意時光。
            </div>
            <div>
                <ul class="room_icon">
                    <li>
                        <i><img src="~/img/use/safe.png" title="保險箱" alt="保險箱"></i>
                        <p>保險箱</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/tv.png" title="液晶電視" alt="液晶電視"></i>
                        <p>液晶電視</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/movie.png" title="黑膠唱盤" alt="黑膠唱盤"></i>
                        <p>黑膠唱盤</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/clean.png" title="浴缸" alt="浴缸"></i>
                        <p>浴缸</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/slippers.png" title="室內皮拖鞋" alt="室內皮拖鞋"></i>
                        <p>室內皮拖鞋</p>
                    </li>
                    <li>
                        <i><img src="~/img/use/bpa-free.png" title="迎賓氣泡水" alt="迎賓氣泡水"></i>
                        <p>迎賓氣泡水</p>
                    </li>
                </ul>
                <div class="roomView">
                    <a asp-controller="Rooms" asp-action="Singleroom"  asp-route-Id="301">VIEW MORE</a>
                </div>
            </div>
        </div>
    </section>
	<br>
    <br>
    <br>
    <div class="back">
        <a asp-controller="Rooms" asp-action="Roomsmasterpage">
            <i class="fas fa-hand-point-left"></i> Back
        </a>
    </div>
</article>